# Generated by Django 4.0.6 on 2023-10-23 10:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.JSONField()),
            ],
            options={
                'db_table': 'attributes_private',
            },
        ),
        migrations.CreateModel(
            name='CommonAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.JSONField()),
            ],
            options={
                'db_table': 'common_attributes_private',
            },
        ),
        migrations.CreateModel(
            name='LicenseAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.JSONField()),
            ],
            options={
                'db_table': 'license_attributes_private',
            },
        ),
        migrations.CreateModel(
            name='LicenseType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.JSONField()),
            ],
            options={
                'db_table': 'license_types_private',
            },
        ),
        migrations.CreateModel(
            name='SoftwareLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('document', models.JSONField()),
            ],
            options={
                'db_table': 'software_licenses_private',
            },
        ),
        migrations.CreateModel(
            name='SoftwareLicenseAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_agreement_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('document', models.JSONField()),
            ],
            options={
                'db_table': 'software_license_agreements_private',
            },
        ),
    ]
