# Generated by Django 4.0.6 on 2022-07-26 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='softwarelicense',
            table='software_licenses',
        ),
        migrations.AlterModelTable(
            name='softwarelicenseagreement',
            table='software_license_agreements',
        ),
    ]
