# Generated by Django 4.0.6 on 2022-07-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0002_alter_softwarelicense_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwarelicense',
            name='license_compatible_with',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='softwarelicense',
            name='license_not_compatible_with',
            field=models.TextField(default=''),
        ),
    ]
