# Generated by Django 4.0.6 on 2022-07-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0003_alter_softwarelicense_license_compatible_with_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwarelicense',
            name='released_date',
            field=models.DateField(null=True),
        ),
    ]
